In [1]:
%pip install mlxtend

Collecting mlxtend
  Using cached mlxtend-0.22.0-py2.py3-none-any.whl (1.4 MB)
Requirement already satisfied: scipy>=1.2.1 in d:\programmes\anaconda3\lib\site-packages (from mlxtend) (1.7.1)
Requirement already satisfied: numpy>=1.16.2 in d:\programmes\anaconda3\lib\site-packages (from mlxtend) (1.20.3)
Requirement already satisfied: pandas>=0.24.2 in d:\programmes\anaconda3\lib\site-packages (from mlxtend) (1.3.4)
Collecting scikit-learn>=1.0.2 (from mlxtend)
  Using cached scikit_learn-1.2.2-cp39-cp39-win_amd64.whl (8.4 MB)
Requirement already satisfied: matplotlib>=3.0.0 in d:\programmes\anaconda3\lib\site-packages (from mlxtend) (3.4.3)
Requirement already satisfied: joblib>=0.13.2 in d:\programmes\anaconda3\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: setuptools in d:\programmes\anaconda3\lib\site-packages (from mlxtend) (58.0.4)
Requirement already satisfied: cycler>=0.10 in d:\programmes\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\programmes\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in d:\programmes\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in d:\programmes\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\abdellatif-kbr\appdata\roaming\python\python39\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in d:\programmes\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Collecting joblib>=0.13.2 (from mlxtend)
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\programmes\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six in d:\programmes\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.16.0)
Installing collected packages: joblib, scikit-learn, mlxtend
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.2
    Uninstalling scikit-learn-0.24.2:
      Successfully uninstalled scikit-learn-0.24.2
Successfully installed joblib-1.2.0 mlxtend-0.22.0 scikit-learn-1.2.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

ImportError: DLL load failed while importing hashing: %1 n’est pas une application Win32 valide.

In [ ]:
df = pd.read_csv('Data/data.csv',
                 header=0,
                 encoding='unicode_escape',
                 dtype={'CustomerID': str,
                        'InvoiceID': str},
                 parse_dates=['InvoiceDate'],
                 infer_datetime_format=True)
df.head()

# Reducing the size of the data set

In [ ]:
sampleData = df.sample(frac=0.3)

sampleData[sampleData["CustomerID"] != 'NaN']

In [5]:
mbAnalysis = sampleData[['CustomerID', 'InvoiceDate', 'Description']]
mbAnalysis.head()

       CustomerID         InvoiceDate                          Description
540158      14606 2011-12-08 19:28:00              BAG 250g SWIRLY MARBLES
319226      15866 2011-08-30 14:09:00        NUMBER TILE COTTAGE GARDEN No
372177      17841 2011-10-02 15:33:00             RED METAL BOX TOP SECRET
367930      17528 2011-09-29 13:45:00     SET OF 3 HANGING OWLS OLLIE BEAK
215566        NaN 2011-06-06 16:06:00  BEADED CRYSTAL HEART GREEN ON STICK

In [6]:
mbAnalysis['single_transaction'] = df['CustomerID'].astype(
    str) + '_' + df['InvoiceDate'].astype(str).str.split(" ").str[0]

mbAnalysis.head()

C:\Users\ABDELL~1\AppData\Local\Temp/ipykernel_3424/2271649286.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mbAnalysis['single_transaction'] = df['CustomerID'].astype(

,CustomerID,InvoiceDate,Description,single_transaction
540158,14606,2011-12-08 19:28:00,BAG 250g SWIRLY MARBLES,14606_2011-12-08
319226,15866,2011-08-30 14:09:00,NUMBER TILE COTTAGE GARDEN No,15866_2011-08-30
372177,17841,2011-10-02 15:33:00,RED METAL BOX TOP SECRET,17841_2011-10-02
367930,17528,2011-09-29 13:45:00,SET OF 3 HANGING OWLS OLLIE BEAK,17528_2011-09-29
215566,NaN,2011-06-06 16:06:00,BEADED CRYSTAL HEART GREEN ON STICK,nan_2011-06-06

In [7]:
df2 = pd.crosstab(mbAnalysis['single_transaction'],
                  mbAnalysis['Description'])
df2.head()

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,water damaged,website fixed,wet damaged,wet pallet,wet rusty,wet/rusty,wet?,wrong barcode,wrong barcode (22467),wrongly marked 23343
single_transaction,,,,,,,,,,,,,,,,,,,,,
12346_2011-01-18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347_2010-12-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347_2011-01-26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347_2011-04-07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347_2011-06-09,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
def encode(item_freq):
    res = 0
    if item_freq > 0:
        res = 1
    return res


basket_input = df2.applymap(encode)

In [16]:
sample_train =  basket_input.sample(frac=0.35,random_state=42)

In [17]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

frequent_itemsets = apriori(sample_train,
                            min_support=0.005,
                            use_colnames=True)

rules = association_rules(frequent_itemsets, metric="lift")

rules

d:\Programmes\Coding\Python\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(JUMBO BAG RED RETROSPOT),(DOTCOM POSTAGE),0.040924,0.009509,0.005094,0.124481,13.090545,0.004705,1.131319,0.963019
1,(DOTCOM POSTAGE),(JUMBO BAG RED RETROSPOT),0.009509,0.040924,0.005094,0.535714,13.090545,0.004705,2.065703,0.932476
2,(ROSES REGENCY TEACUP AND SAUCER ),(GREEN REGENCY TEACUP AND SAUCER),0.021056,0.019528,0.006283,0.298387,15.280014,0.005872,1.397454,0.954656
3,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.019528,0.021056,0.006283,0.321739,15.280014,0.005872,1.443315,0.953168
4,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK POLKADOT),0.040924,0.024283,0.007132,0.174274,7.176914,0.006138,1.181648,0.897389
5,(JUMBO BAG PINK POLKADOT),(JUMBO BAG RED RETROSPOT),0.024283,0.040924,0.007132,0.293706,7.176914,0.006138,1.357900,0.882084
6,(JUMBO BAG RED RETROSPOT),(JUMBO STORAGE BAG SUKI),0.040924,0.022584,0.006113,0.149378,6.614170,0.005189,1.149059,0.885028
7,(JUMBO STORAGE BAG SUKI),(JUMBO BAG RED RETROSPOT),0.022584,0.040924,0.006113,0.270677,6.614170,0.005189,1.315022,0.868422
8,(LUNCH BAG RED RETROSPOT),(JUMBO BAG RED RETROSPOT),0.028188,0.040924,0.005434,0.192771,4.710493,0.004280,1.188109,0.810556
9,(JUMBO BAG RED RETROSPOT),(LUNCH BAG RED RETROSPOT),0.040924,0.028188,0.005434,0.132780,4.710493,0.004280,1.120606,0.821319
10,(JUMBO BAG RED RETROSPOT),(PACK OF 72 RETROSPOT CAKE CASES),0.040924,0.022924,0.005094,0.124481,5.430152,0.004156,1.115997,0.850655
11,(PACK OF 72 RETROSPOT CAKE CASES),(JUMBO BAG RED RETROSPOT),0.022924,0.040924,0.005094,0.222222,5.430152,0.004156,1.233098,0.834984

In [19]:
rules.sort_values(["support", "confidence","lift"],axis = 0, ascending = False).head(8)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
5,(JUMBO BAG PINK POLKADOT),(JUMBO BAG RED RETROSPOT),0.024283,0.040924,0.007132,0.293706,7.176914,0.006138,1.357900,0.882084
4,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK POLKADOT),0.040924,0.024283,0.007132,0.174274,7.176914,0.006138,1.181648,0.897389
3,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.019528,0.021056,0.006283,0.321739,15.280014,0.005872,1.443315,0.953168
2,(ROSES REGENCY TEACUP AND SAUCER ),(GREEN REGENCY TEACUP AND SAUCER),0.021056,0.019528,0.006283,0.298387,15.280014,0.005872,1.397454,0.954656
7,(JUMBO STORAGE BAG SUKI),(JUMBO BAG RED RETROSPOT),0.022584,0.040924,0.006113,0.270677,6.614170,0.005189,1.315022,0.868422
6,(JUMBO BAG RED RETROSPOT),(JUMBO STORAGE BAG SUKI),0.040924,0.022584,0.006113,0.149378,6.614170,0.005189,1.149059,0.885028
8,(LUNCH BAG RED RETROSPOT),(JUMBO BAG RED RETROSPOT),0.028188,0.040924,0.005434,0.192771,4.710493,0.004280,1.188109,0.810556
9,(JUMBO BAG RED RETROSPOT),(LUNCH BAG RED RETROSPOT),0.040924,0.028188,0.005434,0.132780,4.710493,0.004280,1.120606,0.821319